context:
  name: fx-gltf
  version: "2.0.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/jessey-git/fx-gltf/archive/v${{ version }}.tar.gz
    sha256: d044d191f9f6c956bdbaf548d960ae9831fd13dfdc4c82fceefa90cb02a68091
    patches:
      - exclude-apple-from-stdc++fs-linking.patch
      - signed-decode-map.patch
  - url: https://github.com/KhronosGroup/glTF-Sample-Models/archive/2279f7a96e64f76c8bfb306b3b8fd666b2bb93bf.zip
    sha256: be28a164e548775d94f15abd19ec71ca4c22e9e2d66f27757fbab412838360f0
    target_directory: test/data/glTF-Sample-Models

build:
  number: 4
  script:
    - if: win
      then: call "%RECIPE_DIR%\\build.bat"
    - if: unix
      then: bash "${RECIPE_DIR}/build.sh"

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - catch2 >=2.6,<3.0
    - cmake
    - ninja
  host:
    - nlohmann_json
  run:
    - nlohmann_json

tests:
  - requirements:
      run:
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake
        - ninja
    files:
      recipe:
        - test_package/
    script:
      - if: not win
        then:
          - test -f "${PREFIX}/lib/cmake/fx-gltf/fx-gltfConfig.cmake"
          - cmake -S test_package -B test_build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="${PREFIX}"
          - cmake --build test_build --config Release
          - ./test_build/fx_gltf_consumer
      - if: win
        then:
          - if not exist "%PREFIX%\\Library\\lib\\cmake\\fx-gltf\\fx-gltfConfig.cmake" exit 1
          - cmake -S test_package -B test_build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=%LIBRARY_PREFIX%
          - cmake --build test_build --config Release
          - test_build\\fx_gltf_consumer.exe

about:
  homepage: https://github.com/jessey-git/fx-gltf
  repository: https://github.com/jessey-git/fx-gltf
  summary: A C++14/C++17 header-only library for simple, efficient, and robust serialization/deserialization of glTF 2.0
  description: |
    A C++14/C++17 header-only library for simple, efficient, and robust serialization/deserialization of glTF 2.0.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
